ingress:
  enabled: true
  # Used to create an Ingress record.
  className: "ingress-external"
  annotations: 
    alb.ingress.kubernetes.io/load-balancer-name: eks-ingress-external
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /app
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    ## SSL Settings
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:637423397994:certificate/04b7c3cb-336c-4fff-8927-121d119d6656
    # SSL Redirect Setting
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  hosts:
    - name: sonarqube.digitaldense.com
      # Different clouds or configurations might need /* as the default path
      path: /

service:
  type: NodePort

postgresql:
  persistence:
    enabled: false