---
AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC for when GitHub wants to communicate with AWS.
Parameters:
  RepositoryName:
    Type: String
    Description: The name of the GitHub repository
    Default: 'muneebbukhari555/*'

Resources:
  # This is the bare-bones role.
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHub_Actions_CICD_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                ## THESE ARE CASE SENSITIVE!
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${RepositoryName}' #['repo:muneebbukhari555/*']
              StringEqualsIgnoreCase:
                'token.actions.githubusercontent.com:aud': sts.amazonaws.com
      Policies:
        - PolicyName: OidcSafetyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: OidcSafeties
                Effect: Deny
                Action:
                  - sts:AssumeRole
                Resource: "*"

        - PolicyName: GitHubActionsECRPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:        
              - Sid: "AllowPushPull"
                Effect: Allow
                Action:
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:PutImage"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:UploadLayerPart"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:GetAuthorizationToken"
                Resource: "*"
              - Sid: "AllowEKSClusterAccess"
                Effect: Allow
                Action:
                  - "eks:DescribeCluster"
                Resource: "arn:aws:eks:us-east-1:637423397994:cluster/rak-prod-eksdemo"