name: Java Web App
on: 
  push:
    tags:
      - 'v*'

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  checkout_code:
    uses: ./.github/workflows/reusable_checkout.yml
      
  Quality_Check:
    needs: checkout_code
    uses: ./.github/workflows/reusable_quality_check.yml
    secrets:
      APP_NAME: ${{ secrets.APP_NAME }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  Login_AWS_OIDC:
    uses: ./.github/workflows/reusable_aws_oidc_login.yml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
    
  Docker_build_push:
    needs: Quality_Check
    uses: ./.github/workflows/reusable_docker_build_push.yml
    secrets:
      APP_NAME: ${{ secrets.APP_NAME }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

  k8s-deploy:
    needs: Docker_build_push
    uses: ./.github/workflows/reusable_k8s-deploy.yml
    secrets:
      APP_NAME: ${{ secrets.APP_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EKS_Cluster_Name: ${{ secrets.EKS_Cluster_Name }}