name: Java Web App Build and Deploy
on: 
  push:
    tags:
      - 'v*'

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  # Checkout Code
  checkout_code:
    uses: ./.github/workflows/reusable_checkout.yml
  
  # SonarQube Quality Check  
  Quality_Check:
    needs: checkout_code
    uses: ./.github/workflows/reusable_quality_check.yml
    secrets:
      APP_NAME: ${{ secrets.APP_NAME }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  # Building and Pushing Docker Image
  Docker_build_push:
    needs: Quality_Check
    uses: ./.github/workflows/reusable_docker_build_push.yml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      APP_NAME: ${{ secrets.APP_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  
  # Deployment of Application with latest Docker Image
  k8s-deploy:
    needs: Docker_build_push
    uses: ./.github/workflows/reusable_k8s-deploy.yml
    with:
      IMAGE_TAG: ${{needs.Docker_build_push.outputs.IMAGE_TAG_Deploy}}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      APP_NAME: ${{ secrets.APP_NAME }}
      EKS_Cluster_Name: ${{ secrets.EKS_Cluster_Name }}