name: Build and Push Docker Resubale Workflow
on: 
  workflow_call:
    secrets:
      APP_NAME:
        description: THe Name of Application
        required: true
        
      ECR_REGISTRY:
        description: ECR Registry Name
        required: true
        
      ECR_REPOSITORY:
        description: ECR Repository Name
        required: true

jobs:
  checkout_code:
    runs-on: eks_runner
    steps:
      # Checkout Code
      - name: Get code
        uses: actions/checkout@v4

      # Building Docker Context
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders      
      
      # Docker Image MetaData    
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{secrets.ECR_REGISTRY}}/${{secrets.ECR_REPOSITORY}}
          tags: |
            type=semver,pattern={{version}}
      
      # Build, tag, and push docker image to Amazon ECR
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{secrets.APP_NAME}}/
          file: ${{secrets.APP_NAME}}/Dockerfile 
          push: true
          tags: ${{ steps.meta.outputs.tags }}